services:
  mailrelay:
    image: boky/postfix:latest
    container_name: mailrelay
    restart: unless-stopped
    ports:
      - "25:25"
    dns:
      - ${LOCAL_DNS:-1.1.1.1}
    environment:
      - TZ=${TZ:-Europe/Berlin}
      # Variable for the init.sh script
      - SENDER_ADDRESS=${SENDER_ADDRESS}
      # Relay host configuration
      - RELAYHOST=${RELAYHOST}
      - RELAYHOST_USERNAME=${SMTP_USER}
      - RELAYHOST_PASSWORD=${SMTP_PASS}
      - RELAYHOST_USE_TLS=${RELAYHOST_USE_TLS:-yes}
      # Security and network settings
      - ALLOWED_SENDER_DOMAINS=${ALLOWED_SENDER_DOMAINS:-*}
      - MYNETWORKS=${MYNETWORKS}
      # Custom Postfix configuration (injected into main.cf)
      - POSTFIX_sender_canonical_classes=envelope_sender, header_sender
      - POSTFIX_sender_canonical_maps=regexp:/etc/postfix/sender_canonical
      - POSTFIX_smtp_header_checks=regexp:/etc/postfix/header_checks
    volumes:
      # The script is executed on container startup to generate the regex maps
      - ./init.sh:/docker-init.db/init.sh:ro
